//
// PZ-Echo-4x4 -- AmeNote ProtoZOA USB MIDI 2.0 test/reference firmware.
//
// Presents 4 bidirectional MIDI 2.0 GTBs (GTB1..GTB4, Groups 0-3) each with
// its own Function Block (FB1..FB4), plus one bidirectional MIDI 1.0 GTB
// (GTB-M1, Group 4) with its own Function Block (FB-M1). Descriptor
// generated by config.json via the official usbMIDI2DescriptorBuilder --
// see usb_descriptors.cpp.
//
// Behavior:
//  - Responds to a Universal Non-Realtime SysEx Identity Request
//    (F0 7E <id> 06 01 F7) on any group with an Identity Reply, addressed
//    back on the same group it arrived on -- since each of the 5 groups
//    maps 1:1 to its own Function Block, this covers "any group/FB".
//  - Echoes back any Channel Voice message (UMP MT2 -- MIDI 1.0 Channel
//    Voice -- or MT4 -- MIDI 2.0 Channel Voice) unmodified, on the same
//    group/interface it arrived on. Echo is done at the raw-word level
//    (not decoded/re-encoded via umpProcessor's parsed umpCVM struct) so
//    it's lossless for every CV message shape, including ones umpCVM
//    doesn't fully preserve (e.g. MT4 per-note attribute data).
//  - Answers standard UMP Stream Endpoint/Function Block Discovery
//    (umpProcessor) so the device name and each Function Block's name show
//    up correctly in any MIDI 2.0-aware host; GTB/legacy-jack naming for
//    non-UMP-aware tooling is answered by the USB descriptor layer itself
//    (usb_descriptors.cpp).
//  - Answers real MIDI-CI Discovery (F0 7E <id> 0D 70 ... F7) per Function
//    Block, each with its own MUID and its own midiCIProcessor -- template
//    is this same repo's UUT/M2Device_Repro/midi2helper.h umpFunctionBlock
//    class, generalized from its single-instance usage there to 5 real
//    instances (one per Function Block/group), matching the per-FB
//    Discovery Request traffic MIDI2.0Workbench actually sends (confirmed
//    via /Users/rsp_kesumo/midi2workbench's live session log: one Discovery
//    Request per Function Block, addressed on that FB's own group). Profile
//    Configuration/Property Exchange/Process Inquiry are deliberately NOT
//    implemented -- ciSupport is declared 0x00 (Discovery only), honest
//    about what this device actually answers.
//

#include <array>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include "pico/stdlib.h"
#include "pico/unique_id.h"
#include "tusb.h"
#include "ump_device.h"
#include "include/umpProcessor.h"
#include "include/umpMessageCreate.h"
#include "include/midiCIProcessor.h"
#include "include/midiCIMessageCreate.h"

// Responder identity for both UMP Endpoint Device Info and the classic SysEx
// Identity Reply -- 0x7D is the MIDI "Special IDs / non-commercial" SysEx
// manufacturer ID, same convention already used elsewhere in this repo
// (apple_gtb_repro/configs/m2-device-15-1.json's paired main.cpp) since this
// is a test/reference device, not a shipping product.
#define DEVICE_MFRID        0x7D,0x00,0x00
#define DEVICE_FAMID        0x00,0x00
#define DEVICE_MODELID      0x00,0x00
#define DEVICE_VERSIONID    1,0,0,0
#define DEVICE_ENDPOINTNAME "PZ-Echo-4x4"

#define UMP_ITF 0

static umpProcessor UMPHandler;

// One Function Block per GTB/group, each with its own MIDI-CI identity
// (MUID + midiCIProcessor) -- mirrors midi2helper.h's umpFunctionBlock
// class, generalized to a real array of instances instead of that file's
// single gFunctionBlock. `idx` matches this array's own index and is what
// gets embedded in this FB's Discovery Reply (CIMessage::sendDiscoveryReply's
// trailing fbIdx parameter).
struct FunctionBlock
{
    uint8_t     idx;
    const char *name;
    uint8_t     groupStart; // 0-indexed
    bool        midi1Only;
    uint32_t    MUID;
    midiCIProcessor MIDICIHandler;
};

// GTB1..GTB4 = Groups 0-3 (MIDI 2.0 native), GTB-M1 = Group 4 (MIDI 1.0) --
// matches config.json exactly, one Function Block per GTB. MUID is seeded
// at boot in main() (needs runtime entropy); MIDICIHandler default-
// constructs via aggregate init (trailing member omitted from each row).
static FunctionBlock kFunctionBlocks[5] = {
    { 0, "FB1",   0, false, 0 },
    { 1, "FB2",   1, false, 0 },
    { 2, "FB3",   2, false, 0 },
    { 3, "FB4",   3, false, 0 },
    { 4, "FB-M1", 4, true,  0 },
};
static constexpr uint8_t kNumFunctionBlocks = 5;

static void send2(std::array<uint32_t, 2> ump)
{
    if (!tud_ump_n_mounted(UMP_ITF)) return;
    tud_ump_write_hton(UMP_ITF, ump.data(), 2);
}

static void send4(std::array<uint32_t, 4> ump)
{
    if (!tud_ump_n_mounted(UMP_ITF)) return;
    tud_ump_write_hton(UMP_ITF, ump.data(), 4);
}

// --- UMP Stream: Endpoint Discovery -------------------------------------
static void midiEndpointHandler(uint8_t majVer, uint8_t minVer, uint8_t filter)
{
    (void)majVer; (void)minVer;

    if (filter & 0b1) {
        send4(UMPMessage::mtFMidiEndpointInfoNotify(kNumFunctionBlocks, /*m2*/true, /*m1*/true,
                                                      /*rxjr*/false, /*txjr*/false));
    }
    if (filter & 0b10) {
        send4(UMPMessage::mtFMidiEndpointDeviceInfoNotify({DEVICE_MFRID}, {DEVICE_FAMID},
                                                            {DEVICE_MODELID}, {DEVICE_VERSIONID}));
    }
    if (filter & 0b100) {
        int len = strlen(DEVICE_ENDPOINTNAME);
        for (uint8_t offset = 0; offset < len; offset += 14) {
            send4(UMPMessage::mtFMidiEndpointTextNotify(MIDIENDPOINT_NAME_NOTIFICATION, offset,
                                                          (uint8_t *)DEVICE_ENDPOINTNAME, len));
        }
    }
    if (filter & 0b1000) {
        int len = 2 * PICO_UNIQUE_BOARD_ID_SIZE_BYTES + 1;
        uint8_t buff[len];
        pico_get_unique_board_id_string((char *)buff, len);
        for (uint8_t offset = 0; offset < len; offset += 14) {
            send4(UMPMessage::mtFMidiEndpointTextNotify(MIDIENDPOINT_PRODID_NOTIFICATION, offset,
                                                          buff, len));
        }
    }
}

// --- UMP Stream: Function Block Discovery -------------------------------
static void functionBlockHandler(uint8_t fbIdx, uint8_t filter)
{
    for (uint8_t i = 0; i < kNumFunctionBlocks; i++)
    {
        if (fbIdx != i && fbIdx != 0xFF) continue;
        const FunctionBlock &fb = kFunctionBlocks[i];

        if (filter & 0x1) {
            send4(UMPMessage::mtFFunctionBlockInfoNotify(
                i, /*active*/true, /*direction*/3 /*bidi*/, /*sender*/true, /*recv*/true,
                fb.groupStart, /*groupLength*/1, /*midiCISupport*/0x00,
                /*isMIDI1*/ fb.midi1Only ? 1 : 0, /*maxS8Streams*/0));
        }
        if (filter & 0x2) {
            send4(UMPMessage::mtFFunctionBlockNameNotify(i, 0, (uint8_t *)fb.name, strlen(fb.name)));
        }
    }
}

// --- SysEx7 (MT3) reassembly + Identity Request/Reply --------------------
//
// Universal Non-Realtime Identity Request body, F0/F7 already stripped by
// UMP SysEx7 framing (never carried on the wire in UMP form): exactly
// 7E <deviceId> 06 01 (4 bytes). Reply mirrors the requesting deviceId back
// (standard practice) and is addressed on the same group the request
// arrived on -- this is what makes "respond on any group/FB" work, since
// each of the 5 groups maps 1:1 to its own Function Block.
static uint8_t s_sysexBuf[8];
static uint8_t s_sysexLen = 0;
static uint8_t s_sysexGroup = 0;

static uint8_t sxPos = 0;
static std::array<uint8_t, 6> sx;

static void sendOutSysex(uint8_t group, const uint8_t *sysex, uint16_t length, uint8_t state)
{
    if (state < 2) sxPos = 0;
    for (int i = 0; i < length; i++) {
        sx[sxPos++] = sysex[i] & 0x7F;
        if (sxPos == 6) {
            send2(UMPMessage::mt3Sysex7(group, state < 2 && i < 6 ? 1 : 2, 6, sx));
            sxPos = 0;
        }
    }
    if (state == 0 || state == 3) {
        send2(UMPMessage::mt3Sysex7(group, length < 7 && state == 0 ? 0 : 3, sxPos, sx));
    }
}

static void sendIdentityReply(uint8_t group, uint8_t deviceId)
{
    const uint8_t famId[2] = {DEVICE_FAMID};
    const uint8_t modId[2] = {DEVICE_MODELID};
    const uint8_t verId[4] = {DEVICE_VERSIONID};
    uint8_t reply[13] = {
        0x7E, deviceId, 0x06, 0x02,
        0x7D, // manufacturer ID, single byte -- 0x7D is a one-byte Special ID,
              // NOT the 3-byte extended 0x00-prefixed form MIDI-CI always uses.
        famId[0], famId[1],
        modId[0], modId[1],
        verId[0], verId[1], verId[2], verId[3],
    };
    sendOutSysex(group, reply, sizeof(reply), 0);
}

// --- MIDI-CI: per-Function-Block Discovery Reply --------------------------
//
// Seeded from the board's factory-unique ID XORed with the boot-relative
// clock (same spirit as m2-device-15-1/main.cpp's randomMuid()) so the MUID
// differs across boots/boards without a hardware RNG peripheral (RP2040 has
// none).
static void seedRng()
{
    pico_unique_board_id_t boardId;
    pico_get_unique_board_id(&boardId);
    uint32_t seed = (uint32_t)to_us_since_boot(get_absolute_time());
    for (unsigned i = 0; i < PICO_UNIQUE_BOARD_ID_SIZE_BYTES; i++) {
        seed ^= (uint32_t)boardId.id[i] << ((i % 4) * 8);
    }
    srand(seed);
}

// MUID is a 28-bit value on the wire (MIDI-CI spec) -- masking this is not
// optional. mimic_hub's own decisions.md documents a real, previously-shipped
// bug from skipping this mask: an unmasked 32-bit MUID compared correctly
// only when its top nibble happened to be zero (~1-in-16), silently dropping
// every other Discovery Reply with no error. Mask here, matching the
// library's own device-side responder convention (UMP_Endpoint::ensureMUID()
// in mimic_hub/ePercScanner's shared midi_cpp).
static uint32_t randomMuid()
{
    uint32_t v = (uint32_t)rand() & 0x0FFFFFFFu;
    if (v == 0x0FFFFFFFu) v = 0; // avoid the reserved broadcast value
    return v;
}

static bool checkMUIDCallback(uint8_t group, uint32_t muid, FunctionBlock *fb)
{
    (void)group;
    return fb->MUID == muid;
}

static void recvDiscovery(struct MIDICI ciDetails, std::array<uint8_t, 3> manuId,
                           std::array<uint8_t, 2> familyId, std::array<uint8_t, 2> modelId,
                           std::array<uint8_t, 4> version, uint8_t remoteciSupport,
                           uint16_t remotemaxSysex, uint8_t outputPathId, FunctionBlock *fb)
{
    (void)manuId; (void)familyId; (void)modelId; (void)version;
    (void)remoteciSupport; (void)remotemaxSysex;

    uint8_t sysexBuffer[64];
    uint16_t len = CIMessage::sendDiscoveryReply(
        sysexBuffer, /*midiCIVer*/0x02, fb->MUID, ciDetails.remoteMUID,
        {DEVICE_MFRID}, {DEVICE_FAMID}, {DEVICE_MODELID}, {DEVICE_VERSIONID},
        /*ciSupport*/0x00, /*sysExMax*/512, outputPathId, fb->idx);
    sendOutSysex(ciDetails.umpGroup, sysexBuffer, len, 0);
}

// True while a MIDI-CI SysEx7 stream (Universal Non-RT 0x7E + MIDI-CI
// sub-ID1 0x0D) is being reassembled -- detected on the Start/Complete
// packet, same technique as M2Device_Repro/main.cpp's handle_sysex7(), but
// operating on umpProcessor's already-reassembled struct umpData instead of
// re-parsing raw UMP words. s_ciGroup selects which Function Block's own
// midiCIProcessor owns this stream (each group maps 1:1 to one FB here).
static bool    s_ciInProgress = false;
static uint8_t s_ciGroup = 0;

static void processUMPSysex(struct umpData mess)
{
    if (mess.form == 0 || mess.form == 1) {
        s_ciInProgress = (mess.dataLength >= 3 && mess.data[0] == 0x7E && mess.data[2] == 0x0D);
        if (s_ciInProgress) {
            s_ciGroup = mess.umpGroup;
            if (s_ciGroup < kNumFunctionBlocks) {
                kFunctionBlocks[s_ciGroup].MIDICIHandler.startSysex7(s_ciGroup, mess.data[1]);
            }
        }
    }
    if (s_ciInProgress && s_ciGroup < kNumFunctionBlocks) {
        for (uint8_t i = 0; i < mess.dataLength; i++) {
            kFunctionBlocks[s_ciGroup].MIDICIHandler.processMIDICI(mess.data[i]);
        }
        if (mess.form == 0 || mess.form == 3) {
            kFunctionBlocks[s_ciGroup].MIDICIHandler.endSysex7();
            s_ciInProgress = false;
        }
        return; // MIDI-CI traffic doesn't fall through to the classic path below
    }

    if (mess.form == 0 || mess.form == 1) {
        s_sysexLen = 0;
        s_sysexGroup = mess.umpGroup;
    }
    for (uint8_t i = 0; i < mess.dataLength && s_sysexLen < sizeof(s_sysexBuf); i++) {
        s_sysexBuf[s_sysexLen++] = mess.data[i];
    }
    if (mess.form == 0 || mess.form == 3) {
        if (s_sysexLen == 4 && s_sysexBuf[0] == 0x7E && s_sysexBuf[2] == 0x06 && s_sysexBuf[3] == 0x01) {
            sendIdentityReply(s_sysexGroup, s_sysexBuf[1]);
        }
        s_sysexLen = 0;
    }
}

// --- Raw-word dispatch ----------------------------------------------------
//
// MT2/MT4 Channel Voice: echoed back immediately at the raw-word level.
// Everything else (SysEx7, UMP Stream, Utility/System/etc.) is routed
// through umpProcessor so the handlers registered above (Endpoint/
// FunctionBlock discovery, Identity Request) fire.
static uint8_t words_needed_for_mt(uint8_t mt)
{
    switch (mt)
    {
        case 0x0: case 0x1: case 0x2: case 0x6: case 0x7: return 1; // 32-bit
        case 0x3: case 0x4: case 0x8: case 0x9:           return 2; // 64-bit
        case 0xA: case 0xB: case 0xC:                     return 3; // 96-bit
        case 0x5: case 0xD: case 0xF:                     return 4; // 128-bit
        default:                                          return 1;
    }
}

static void poll_ump()
{
    static uint32_t rxWords[4];
    static uint8_t  rxCount = 0;
    static uint8_t  rxNeeded = 1;

    while (tud_ump_n_mounted(UMP_ITF) && tud_ump_n_available(UMP_ITF) >= 1 && rxCount < rxNeeded)
    {
        uint32_t w;
        if (tud_ump_read_ntoh(UMP_ITF, &w, 1) != 1) break;
        rxWords[rxCount++] = w;
        if (rxCount == 1)
        {
            rxNeeded = words_needed_for_mt((uint8_t)(w >> 28));
        }
        if (rxCount >= rxNeeded)
        {
            uint8_t mt = (uint8_t)(rxWords[0] >> 28);
            if (mt == 0x2 || mt == 0x4)
            {
                // Channel Voice -- echo the raw word(s) back unmodified.
                tud_ump_write_hton(UMP_ITF, rxWords, rxNeeded);
            }
            else
            {
                for (uint8_t i = 0; i < rxNeeded; i++) UMPHandler.processUMP(rxWords[i]);
            }
            rxCount = 0;
            rxNeeded = 1;
        }
    }
}

int main()
{
    stdio_init_all();
    tusb_init();
    seedRng();

    UMPHandler.setMidiEndpoint(midiEndpointHandler);
    UMPHandler.setFunctionBlock(functionBlockHandler);
    UMPHandler.setSysEx(processUMPSysex);

    for (uint8_t i = 0; i < kNumFunctionBlocks; i++) {
        FunctionBlock *fb = &kFunctionBlocks[i];
        fb->MUID = randomMuid();
        fb->MIDICIHandler.setCheckMUID(
            std::bind(checkMUIDCallback, std::placeholders::_1, std::placeholders::_2, fb));
        fb->MIDICIHandler.setRecvDiscovery(
            std::bind(recvDiscovery, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3,
                      std::placeholders::_4, std::placeholders::_5, std::placeholders::_6,
                      std::placeholders::_7, std::placeholders::_8, fb));
    }

    while (true)
    {
        tud_task();
        poll_ump();
    }

    return 0;
}

void tud_ump_set_itf_cb(uint8_t itf, uint8_t alt)
{
    (void) itf;
    printf("UMP on USB enabled: %d \n", alt);
}
