/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Ha Thach (tinyusb.org)
 * Copyright (c) 2022 Michael Loh (AmeNote.com)
 * Copyright (c) 2022 Franz Detro (native-instruments.de)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

#include "tusb.h"
#include "pico/unique_id.h"
#include "ump_device.h"

// ---------------------------------------------------------------------------
// desc_device[], desc_device_qualifier[], desc_fs_configuration[], gtb0[]...,
// gtbLengths[], epInterface[], group_descr[], string_desc_arr[] and
// string_desc_arr_length are generated by the MIDI Association's own
// USB MIDI 2.0 Descriptor Builder (github.com/midi2-dev/usbMIDI2DescriptorBuilder,
// buildUSBDescriptors.js:buildTinyUSBDescriptors()), run headlessly via Node
// from config.json (this directory). This file only supplies the fixed
// TinyUSB glue callbacks below -- edit config.json + regenerate
// (apple_gtb_repro/scripts/gen_descriptors.js) to change the GTB layout, do
// not hand-edit the generated descriptor bytes. Mirrors
// UUT_FreeRTOS/USB_MIDI_Echo/usb_descriptors.cpp's approach exactly.
// ---------------------------------------------------------------------------
#include "generated_descriptors.inc"

// Invoked when received GET DEVICE DESCRIPTOR
uint8_t const * tud_descriptor_device_cb(void)
{
  return desc_device;
}

// Invoked when received GET CONFIGURATION DESCRIPTOR
uint8_t const * tud_descriptor_configuration_cb(uint8_t index)
{
  (void) index;
  return desc_fs_configuration;
}

// Invoked when received GET DEVICE QUALIFIER DESCRIPTOR request
uint8_t const* tud_descriptor_device_qualifier_cb(void)
{
  return desc_device_qualifier;
}

//--------------------------------------------------------------------+
// String Descriptors
//--------------------------------------------------------------------+
static uint16_t _desc_str[32];

// Invoked when received GET STRING DESCRIPTOR request
uint16_t const* tud_descriptor_string_cb(uint8_t index, uint16_t langid)
{
  (void) langid;

  uint8_t chr_count;

  if ( index == 0 )
  {
    // Generator's string_desc_arr[0] is a placeholder (""), not the raw
    // langid bytes -- the language ID response is synthesized here instead.
    _desc_str[1] = 0x0409; // English (US)
    chr_count = 1;
  }
  else
  {
    if ( !(index < string_desc_arr_length) ) return NULL;

    const char* str = string_desc_arr[index];

    chr_count = strlen(str);
    if ( chr_count > 31 ) chr_count = 31;

    for (uint8_t i = 0; i < chr_count; i++)
    {
      _desc_str[1+i] = str[i];
    }
  }

  _desc_str[0] = (TUSB_DESC_STRING << 8) | (2*chr_count + 2);

  return _desc_str;
}

//--------------------------------------------------------------------+
// Group Terminal Block Descriptor
//--------------------------------------------------------------------+

// Routes by wIndex (the target interface number) against the generator's own
// epInterface[]/group_descr[] arrays. Length comes from each blob's own
// wTotalLength header field (bytes 3-4, little-endian) rather than the
// generator's separate gtbLengths[], which is declared uint8_t and silently
// overflows/truncates past ~19 blocks -- not a risk for this device's 5
// blocks, but reading it from the blob itself is correct regardless of size
// and matches the established pattern in this repo
// (UUT_FreeRTOS/USB_MIDI_Echo/usb_descriptors.cpp).
bool tud_ump_get_req_itf_cb(uint8_t rhport, tusb_control_request_t const * request)
{
  if ( request->wValue != 0x2601 ) return false; //0x26 - CS_GR_TRM_BLOCK 0x01 - alternate interface setting

  uint8_t itf_num = (uint8_t)(request->wIndex & 0xFF);
  unsigned kNumFunctions = sizeof(epInterface) / sizeof(epInterface[0]);
  for (unsigned i = 0; i < kNumFunctions; i++)
  {
    if (epInterface[i] != itf_num) continue;

    const uint8_t* gtb = group_descr[i];
    uint16_t gtb_len = (uint16_t)(gtb[3] | (gtb[4] << 8)); // wTotalLength, LE
    uint16_t length = request->wLength;
    if ( length > gtb_len ) length = gtb_len;
    tud_control_xfer(rhport, request, (void *) gtb, length );
    return true;
  }
  return false;
}
